### ISSUE TITLE
Modifyworld won't load on 1.12-pre5

### ISSUE THREAD

**Issue by PsychoLynx** [PEXPlugins/Modifyworld#119]
When trying to run Modifyworld on the new 1.12-pre5 Spigot, this error gets printed:

[16:01:52] [Server thread/INFO]: [Modifyworld] Enabling Modifyworld v1.19.7
[16:01:52] [Server thread/ERROR]: Error occurred while enabling Modifyworld v1.19.7 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at ru.tehkode.modifyworld.bukkit.Modifyworld.reloadConfig(Modifyworld.java:160) ~[?:?]
	at ru.tehkode.modifyworld.bukkit.Modifyworld.getConfig(Modifyworld.java:122) ~[?:?]
	at ru.tehkode.modifyworld.bukkit.Modifyworld.onEnable(Modifyworld.java:65) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12-pre5.jar:git-Spigot-5b8313f-1004352]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by uncovery** [comment]
Is there a Jar file available of that version?

**Comment by bigsmileling** [comment]
@uncovery https://ci.destroystokyo.com/job/PaperSpigot/1106/ On paperspigot doesnt work

**Comment by kodji** [comment]
on spigot 1.12 doesnt work :(

**Comment by shad1w** [comment]
I'll soon have to update and might try to fix this.

**Comment by uncovery** [comment]
there is a release here: https://github.com/games647/Modifyworld/releases

**Comment by shad1w** [comment]
Thank you, didn't see this.

**Comment by ScuroK** [comment]
PLS post the update to the project page aswell for all the user who dont know!
